services:
  user-crud-auth-go:
    container_name: user-crud-auth-go-dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../..:/app
      - /app/tmp
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    working_dir: /app
    restart: unless-stopped
